### ISSUE TITLE
Allow previewing any CSV file

### ISSUE THREAD

**Issue by dufferzafar** [wrgl/wrgl#4]
`wrgl` has a nice preview command which can show the CSV file in a table TUI, but the preview command takes a commit / branch name.

Preview should work for any generic file - whether or not it has been committed to the repo.

This will allow me to view the CSV file before committing - say to figure out its primary key etc.

**Comment by pckhoi** [comment]
Thank you for your suggestion! It is a worthwhile change for sure.

**Comment by pckhoi** [comment]
@dufferzafar can you check that the latest version does what you expect?

**Comment by dufferzafar** [comment]
Yup, I had a look at the commit. Will check with a bunch of CSV files that I have & confirm later.

**Comment by pckhoi** [comment]
I will open again when you see an issue.
