### ISSUE TITLE
Transpose one row in previewer

### ISSUE THREAD

**Issue by dufferzafar** [wrgl/wrgl#6]
https://www.visidata.org/ also has a TUI to show CSV data, which allows to view a single row in a "transpose" view. Where the columns become rows and the row data becomes a single column. This allows to view any particular row in detail.

**Comment by pckhoi** [comment]
I see that you are describing single row transpose. Thank you for your suggestion. I will think about it and get back to you later.

**Comment by pckhoi** [comment]
I hardly see this feature as standing on its own. How are you planning to use Wrgl? What other features do you think are missing? e.g. filter, pivot, sort, etc...

**Comment by dufferzafar** [comment]
I don't plan to use `wrgl` for it's repo like features - commit etc.

But I needed a static binary version of a CSV viewer (Visidata is a Python application, so needs to be installed on each box)

Now that you've implemented the preview functionality on a csv file, that is what I plan to use the most - to view arbitrary CSV files on command line.

**Comment by pckhoi** [comment]
Closing because it does not align with wrgl's core value proposition at this moment.
