### ISSUE TITLE
Unexpected EOF when pushing objects

### ISSUE THREAD

**Issue by pckhoi** [wrgl/wrgl#8]
From Ayyub:

> The local outputs of `fuse/personnel.csv` and `fuse/person.csv` are different from those on WRGL after a successful PR and transaction application. While exploring the issue, I attempted to push the files manually. Below is the output that I refer to above:
> 
> ```
> ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl pull personnel origin refs/heads/personnel:refs/remotes/origin/personnel --set-upstream     
> Fetching objects 36082 / -1 [                                                                                                                              ] 1m41s
> From https://wrgl.llead.co
>  * [new branch]      personnel   -> origin/personnel
> branch "personnel" setup to track remote branch "personnel" from "origin"
> 
> [personnel 30b963e] commit [tx/e32092c6-6d26-4ff1-8ed7-0f11f7110283]
> [PR #545: enhancement/richland_so][1]
> 
> [1]: https://github.com/ipno-llead/processing/pull/545
> ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl pull person origin refs/heads/person:refs/remotes/origin/person --set-upstream
> Fetching objects 45179 / -1 [                                                                                                                              ] 2m13s
> From https://wrgl.llead.co
>  * [new branch]      person      -> origin/person
> branch "person" setup to track remote branch "person" from "origin"
> 
> [person e9fdb4b] commit [tx/14c39db8-5fb5-43a7-bd1c-56d2ed153f48]
> [PR #549: fix: person][1]
> 
> [1]: https://github.com/ipno-llead/processing/pull/549
> ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit personnel data/fuse/personnel.csv "manually pushed personnel table" -p uid --set-file --set-primary-key
> saving blocks 388 / 388 [=====================================================================================================================================] 0s
> [personnel 208c8d8] manually pushed personnel table
> ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit person data/fuse/person.csv "manually pushed person table" -p uid --set-file --set-pr
> imary-key
> key "uid" not found in string slice
> ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit person data/fuse/person.csv "manually pushed person table" --set-file --set-primary-k
> ey
> saving blocks 388 / 388 [=====================================================================================================================================] 0s
> [person e363591] manually pushed person table
> ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl push origin refs/heads/personnel:personnel --set-upstream
> To https://wrgl.llead.co
> Visit https://keycloak.llead.co/realms/llead-wrgl/device in your browser and enter user code "AXKP-ZYZR" to login
> 
> Saved credentials to /home/ayyubi/.config/wrgl/credentials.yaml
> Pushing objects 189 / 189 [=====================================================================================================================================] 
> unexpected EOF
> ```

**Comment by pckhoi** [comment]
Looks like the error happened when you commit with the `--set-primary-key` flag without the primary key.

**Comment by ayyubibrahimi** [comment]
Not sure I follow.

Is the command above incorrect? I.e., 

`ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit personnel data/fuse/personnel.csv "manually pushed personnel table" -p uid --set-file --set-primary-key`

`ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl push origin refs/heads/personnel:personnel --set-upstream`

Although I haven't attempted to push it yet, I see that the `person` table has `person_id` as its primary key, which is missing from the code above.

**Comment by pckhoi** [comment]
Yes, please set the correct primary key for that table. `-p <column_name>` means using that column as the primary key. Calling `--set-primary-key` without specifying a primary key makes no sense either. Let me know if that makes sense.

**Comment by ayyubibrahimi** [comment]
Yes, that makes sense. But I did set the primary key for the personnel table above, which returned the error. I've just re-run the code for both the `personnel` and `person` tables:

```
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit personnel data/fuse/personnel.csv "manually pushed personnel table" -p uid --set-file --set-primary-key
saving blocks 388 / 388 [========================================================================================================================================] 0s
[personnel 7056665] manually pushed personnel table
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit person data/fuse/person.csv "manually pushed person table" -p person_id --set-file --set-pr
unknown flag: --set-pr
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit person data/fuse/person.csv "manually pushed person table" -p person_id --set-file --set-primary-key
saving blocks 375 / 375 [========================================================================================================================================] 0s
[person bccbb25] manually pushed person table
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl push origin refs/heads/personnel:personnel --set-upstream
To https://wrgl.llead.co
Pushing objects 189 / 189 [========================================================================================================================================] 
unexpected EOF
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl push origin refs/heads/person:person --set-upstream
To https://wrgl.llead.co
Pushing objects 197 / 197 [========================================================================================================================================] 
unexpected EOF
```

**Comment by pckhoi** [comment]
Yes, then there's an issue. Could you share the `person.csv` file with me?

**Comment by ayyubibrahimi** [comment]
[person.csv](https://github.com/wrgl/wrgl/files/12408973/person.csv)
[personnel.csv](https://github.com/wrgl/wrgl/files/12408976/personnel.csv)
Attached.

**Comment by pckhoi** [comment]
@ayyubibrahimi so there could be an issue with the commit cache. Could you install the latest wrgl cli and then re-commit with flag `--no-cache`?

**Comment by ayyubibrahimi** [comment]
@pckhoi Thanks for continuing to look into this. Please see the output below for the `person` table (I haven't yet run this for the `personnel` table). 

Although the code runs without error, and although and WRGL is updated (at least based on the commit message), the person table on WRGL does not mirror my local `person` table. 

```
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl fetch origin refs/heads/person:refs/remotes/origin/person
From https://wrgl.llead.co
   c355bfb..76c4f54  person      -> origin/person
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl branch create persons_new person
created branch persons_new (76c4f5481bad0c91f9721d82670678d4)
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl merge persons_new origin/person
All commits are identical, nothing to merge
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl commit persons_new data/fuse/person.csv "manually pushed person table" -p person_id --set-file --set-primary-key --no-cache
saving blocks 375 / 375 [==========================================================================================================================================] 0s
[persons_new ceb91e7] manually pushed person table
ayyubi@IPNO20230128:/mnt/c/Users/ayyubi/Desktop/wrgl/processing$ wrgl push origin refs/heads/persons_new:person --set-upstream
To https://wrgl.llead.co
Pushing objects 200 / 200 [==========================================================================================================================================] 
Sending packfile 18.31 KiB / 18.31 KiB [========================================================================================================================] 100 %
   76c4f54..ceb91e7  persons_new -> person
branch "persons_new" setup to track remote branch "person" from "origin"
```

Also, here is the output when I attempt to manually commit the table on wrgl.co:

`503: "<!DOCTYPE html>\n<html>\n <head>\n <title>503 Backend fetch failed</title>\n </head>\n <body>\n <h1>Error 503 Backend fetch failed</h1>\n <p>Backend fetch failed</p>\n <h3>Guru Meditation:</h3>\n <p>XID: 1443410</p>\n <hr>\n <p>Varnish cache server</p>\n </body>\n</html>\n"`

**Comment by pckhoi** [comment]
So the data is not committed as is but is transformed in the following ways:
- rows are deduplicated based on the primary key
- rows are sorted by the primary key

So it is not really any surprise that those files are not identical. Even if the commit via the webpage went through successfully, the same transformations would still apply. I guess this issue is resolved then.
